/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ELETRO;

import javax.swing.JOptionPane;

import Usuarios.Agua.ComercioLocalAE;
import Usuarios.Agua.CooperativaRuralAE;
import Usuarios.Agua.OutrosAE;
import Usuarios.Agua.ResidencialAE;
import Usuarios.Agua.ResidencialRuralAE;
import Usuarios.Agua.ResidencialSocialAE;
import Usuarios.Agua.ServicoPublicoAE;
import Usuarios.Agua.ServicoTurismoAE;
import Usuarios.Energia.ComercioLocal;
import Usuarios.Energia.CooperativaRural;
import Usuarios.Energia.Outros;
import Usuarios.Energia.Residencial;
import Usuarios.Energia.ResidencialRural;
import Usuarios.Energia.ResidencialSocial;
import Usuarios.Energia.ServicoPublico;
import Usuarios.Energia.ServicoTurismo;

/**
 *
 * @author 021623
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        TxtConsumo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Comercio = new javax.swing.JButton();
        turismo = new javax.swing.JButton();
        Governo = new javax.swing.JButton();
        Outros = new javax.swing.JButton();
        cooperativa = new javax.swing.JButton();
        Rural = new javax.swing.JButton();
        BaixaRenda = new javax.swing.JButton();
        residencial = new javax.swing.JButton();
        AGUA = new javax.swing.JLabel();
        TxtConsumoAE = new javax.swing.JTextField();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        TxtConsumo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TxtConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtConsumoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Energia (Kwh)");

        Comercio.setText("Comercio");
        Comercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComercioActionPerformed(evt);
            }
        });

        turismo.setText("Turismo");
        turismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turismoActionPerformed(evt);
            }
        });

        Governo.setText("Serviço publico");
        Governo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GovernoActionPerformed(evt);
            }
        });

        Outros.setText("Outros");
        Outros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutrosActionPerformed(evt);
            }
        });

        cooperativa.setText("Cooperativa");
        cooperativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cooperativaActionPerformed(evt);
            }
        });

        Rural.setText("Rural");
        Rural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuralActionPerformed(evt);
            }
        });

        BaixaRenda.setText("Baixa Renda");
        BaixaRenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaixaRendaActionPerformed(evt);
            }
        });

        residencial.setText("Residencial");
        residencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residencialActionPerformed(evt);
            }
        });

        AGUA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AGUA.setText("Agua (M³)");

        TxtConsumoAE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TxtConsumoAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtConsumoAEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(AGUA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtConsumo)
                            .addComponent(TxtConsumoAE, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Governo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Comercio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rural, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(residencial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BaixaRenda, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(cooperativa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(turismo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Outros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(TxtConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AGUA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtConsumoAE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(residencial)
                    .addComponent(BaixaRenda))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rural)
                    .addComponent(cooperativa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turismo)
                    .addComponent(Comercio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Governo)
                    .addComponent(Outros))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtConsumoActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_TxtConsumoActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void residencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residencialActionPerformed
        Residencial out = new Residencial  (Integer.parseInt(TxtConsumo.getText() ) );
        JOptionPane.showMessageDialog(null, out,"Boleto",HEIGHT);
        ResidencialAE ou = new ResidencialAE (Integer.parseInt(TxtConsumoAE.getText()));
        JOptionPane.showConfirmDialog(null, ou,"Boleto",HEIGHT);
        float totalApagar = out.getTotalApagar();
        float totalApagar2 = ou.getTotalApagar();
        float Resultado = totalApagar + totalApagar2;
        JOptionPane.showConfirmDialog(null,String.format("\n Valor a pagar R$ %.2f%n",Resultado) ,"Total a Pagar",HEIGHT); 
          
         
    }//GEN-LAST:event_residencialActionPerformed

    private void BaixaRendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaixaRendaActionPerformed
      ResidencialSocial out = new ResidencialSocial (Integer.parseInt(TxtConsumo.getText() ) );
      JOptionPane.showMessageDialog(null, out,"Boleto",HEIGHT);
      ResidencialSocialAE ou = new ResidencialSocialAE (Integer.parseInt(TxtConsumoAE.getText() ) );
      JOptionPane.showMessageDialog(null, ou,"Boleto",HEIGHT);
      float totalApagar = out.getTotalApagarbr();
      float totalApagar2 = ou.getTotalApagarbr();
      float Resultado = totalApagar + totalApagar2;
      JOptionPane.showConfirmDialog(null,String.format("\n Valor a pagar R$ %.2f%n",Resultado) ,"Total a Pagar",HEIGHT);
    }//GEN-LAST:event_BaixaRendaActionPerformed

    private void GovernoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GovernoActionPerformed
          ServicoPublico out = new ServicoPublico  (Integer.parseInt(TxtConsumo.getText() ) );
          JOptionPane.showMessageDialog(null, out,"Boleto",HEIGHT);
          ServicoPublicoAE ou = new ServicoPublicoAE  (Integer.parseInt(TxtConsumoAE.getText() ) );
          JOptionPane.showMessageDialog(null, ou,"Boleto",HEIGHT);
          float totalApagar = out.getTotalApagar4();
          float totalApagar2 = ou.getTotalApagar4();
          float Resultado = totalApagar + totalApagar2;
          JOptionPane.showConfirmDialog(null,String.format("\n Valor a pagar R$ %.2f%n",Resultado) ,"Total a Pagar",HEIGHT);
    }//GEN-LAST:event_GovernoActionPerformed

    private void OutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutrosActionPerformed
       Outros out = new Outros(Integer.parseInt(TxtConsumo.getText())); 
       JOptionPane.showMessageDialog(null, out,"Boleto",HEIGHT);
       OutrosAE ou = new OutrosAE(Integer.parseInt(TxtConsumoAE.getText())); 
       JOptionPane.showMessageDialog(null, ou,"Boleto",HEIGHT);
          
    }//GEN-LAST:event_OutrosActionPerformed

    private void RuralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuralActionPerformed
          ResidencialRural out = new ResidencialRural  (Integer.parseInt(TxtConsumo.getText() ) );
          JOptionPane.showMessageDialog(null, out,"Boleto",HEIGHT);
          ResidencialRuralAE ou = new ResidencialRuralAE  (Integer.parseInt(TxtConsumoAE.getText() ) );
          JOptionPane.showMessageDialog(null, ou,"Boleto",HEIGHT);
          float totalApagar = out.getTotalApagar();
          float totalApagar2 = ou.getTotalApagar();
          float Resultado = totalApagar + totalApagar2;
          JOptionPane.showConfirmDialog(null,String.format("\n Valor a pagar R$ %.2f%n",Resultado) ,"Total a Pagar",HEIGHT);
    }//GEN-LAST:event_RuralActionPerformed

    private void ComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComercioActionPerformed
      ComercioLocal out = new ComercioLocal  (Integer.parseInt(TxtConsumo.getText() ) );
      JOptionPane.showMessageDialog(null, out,"Boleto",HEIGHT);
      ComercioLocalAE ou = new ComercioLocalAE (Integer.parseInt(TxtConsumoAE.getText()));
      JOptionPane.showConfirmDialog(null, ou,"Boleto",HEIGHT);
    }//GEN-LAST:event_ComercioActionPerformed

    private void cooperativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cooperativaActionPerformed
     CooperativaRural out = new CooperativaRural  (Integer.parseInt(TxtConsumo.getText() ) );
     JOptionPane.showMessageDialog(null, out,"Boleto",HEIGHT);
     CooperativaRuralAE ou = new CooperativaRuralAE  (Integer.parseInt(TxtConsumoAE.getText() ) );
     JOptionPane.showMessageDialog(null, ou,"Boleto",HEIGHT);
     float totalApagar = out.getTotalApagar1();
     float totalApagar2 = ou.getTotalApagar1();
     float Resultado = totalApagar + totalApagar2;
     JOptionPane.showConfirmDialog(null,String.format("\n Valor a pagar R$ %.2f%n",Resultado) ,"Total a Pagar",HEIGHT);
    }//GEN-LAST:event_cooperativaActionPerformed

    private void turismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turismoActionPerformed
     ServicoTurismo out = new ServicoTurismo (Integer.parseInt(TxtConsumo.getText() ) );
     JOptionPane.showMessageDialog(null, out,"Boleto",HEIGHT);
     ServicoTurismoAE ou = new ServicoTurismoAE (Integer.parseInt(TxtConsumoAE.getText() ) );
     JOptionPane.showMessageDialog(null, ou,"Boleto",HEIGHT);
     float totalApagar = out.getTotalApagar3();
     float totalApagar2 = ou.getTotalApagar3();
     float Resultado = totalApagar + totalApagar2;
     JOptionPane.showConfirmDialog(null,String.format("\n Valor a pagar R$ %.2f%n",Resultado) ,"Total a Pagar",HEIGHT);
    }//GEN-LAST:event_turismoActionPerformed

    private void TxtConsumoAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtConsumoAEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtConsumoAEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AGUA;
    private javax.swing.JButton BaixaRenda;
    private javax.swing.JButton Comercio;
    private javax.swing.JButton Governo;
    private javax.swing.JButton Outros;
    private javax.swing.JButton Rural;
    private javax.swing.JTextField TxtConsumo;
    private javax.swing.JTextField TxtConsumoAE;
    private javax.swing.JButton cooperativa;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.ButtonGroup menu;
    private javax.swing.JButton residencial;
    private javax.swing.JButton turismo;
    // End of variables declaration//GEN-END:variables
}
